'use strict'
try{
    //x = 10;
    //mifuncion();
    let y = 9;

}
catch(error){
    console.log(error);
}
//bloque opcional
finally{
    console.log('termina la revision de errores');
}
console.log('continuamos')